#pragma once
#ifndef ANOTHER_DND_SIMULATOR_TEST_H
#define ANOTHER_DND_SIMULATOR_TEST_H
#include "battleground_test.h"
#include "character_test.h"
#include "classes_test.h"
#include "race_test.h"
#include "item_test.h"
#endif //ANOTHER_DND_SIMULATOR_TEST_H
